apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-consumer
  template:
    metadata:
      labels:
        app: go-consumer
    spec:
      containers:
      - name: go-consumer
        image: 34.136.113.161:8080/go-consumer:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: VALKEY_ADDR
          value: "valkey:6379"
