apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rust
  template:
    metadata:
      labels:
        app: api-rust
    spec:
      containers:
      - name: api-rust
        image: us-central1-docker.pkg.dev/deep-clock-500019-v8/quiniela-repo/api-rust:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GO_CLIENT_URL
          value: "http://go-client:8081/"
        resources:
          requests:
            cpu: "100m" # Requerido para que el HPA pueda calcular el %
          limits:
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-rust
spec:
  selector:
    app: api-rust
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-rust-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-rust
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
